CREATE TABLE usuarios(
            id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
            nome VARCHAR(100) NOT NULL,
            email VARCHAR(100) NOT NULL UNIQUE,
            senha VARCHAR(100) NOT NULL
);