create table pacientes(
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nome varchar(100) not null,
        email varchar(100) not null unique,
        telefone varchar(100) not null unique,
        cpf varchar(14) not null unique
);