create table consultas(

    id bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    medico_id bigint not null,
    paciente varchar(100) not null,
    data DATE not null,

    constraint fk_consultas_medico_id foreign key(medico_id) references medicos(id)

);